# Generated by Django 3.1.4 on 2020-12-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Userid')),
                ('name', models.CharField(max_length=140)),
                ('surname', models.CharField(max_length=140)),
                ('idcard', models.CharField(max_length=14)),
                ('commencementday', models.DateField()),
                ('email', models.EmailField(max_length=140)),
                ('telphoneNumber', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
