# Generated by Django 3.1.5 on 2021-01-13 15:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentcode', models.IntegerField(primary_key=True, serialize=False, verbose_name='Studentcode')),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=6)),
                ('name', models.CharField(max_length=140)),
                ('surname', models.CharField(max_length=140)),
                ('idcard', models.CharField(max_length=13)),
                ('commencementday', models.DateField(null=True)),
                ('email', models.EmailField(max_length=140)),
                ('telphoneNumber', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skillid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languagename', models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('Html', 'Html'), ('C', 'C'), ('JavaScript', 'JavaScript'), ('C++', 'C++'), ('C#', 'C#')], max_length=140)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('studentname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='students.student')),
            ],
            options={
                'ordering': ['languagename'],
            },
        ),
    ]
