# Generated by Django 3.1.5 on 2021-02-13 17:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('workid', models.AutoField(primary_key=True, serialize=False, verbose_name='WorkId')),
                ('name', models.CharField(max_length=140, verbose_name='WorkName')),
                ('detail', models.CharField(max_length=1000)),
                ('accountid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['workid'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.AutoField(primary_key=True, serialize=False, verbose_name='StudentId')),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=6)),
                ('name', models.CharField(max_length=140, verbose_name='firstName')),
                ('surname', models.CharField(max_length=140)),
                ('idcard', models.CharField(max_length=13)),
                ('commencementday', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=140)),
                ('telphoneNumber', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('accountid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skillid', models.AutoField(primary_key=True, serialize=False, verbose_name='SkillId')),
                ('name', models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('Html', 'Html'), ('C', 'C'), ('JavaScript', 'JavaScript'), ('C++', 'C++'), ('C#', 'C#')], max_length=140, verbose_name='SkillName')),
                ('score', models.DecimalField(decimal_places=20, default=0.0, max_digits=30, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='SkillScore')),
                ('sumscore', models.DecimalField(blank=True, decimal_places=0, max_digits=30, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='SkillSumScore')),
                ('accountid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('pictureid', models.AutoField(primary_key=True, serialize=False, verbose_name='PictureId')),
                ('picturefile', models.FileField(null=True, upload_to='')),
                ('accountid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pictureid'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('languageid', models.AutoField(primary_key=True, serialize=False, verbose_name='LanguageId')),
                ('name', models.CharField(choices=[('กัมพูชา', 'กัมพูชา'), ('กาตาร์', 'กาตาร์'), ('เกาหลีใต้', 'เกาหลีใต้'), ('เกาหลีเหนือ', 'เกาหลีเหนือ'), ('คาซัคสถาน', 'คาซัคสถาน'), ('คีร์กีซสถาน', 'คีร์กีซสถาน'), ('คูเวต', 'คูเวต'), ('จอร์เจีย', 'จอร์เจีย'), ('จอร์แดน', 'จอร์แดน'), ('จีน', 'จีน'), ('ซาอุดีอาระเบีย', 'ซาอุดีอาระเบีย'), ('ซีเรีย', 'ซีเรีย'), ('ไซปรัส', 'ไซปรัส'), ('ญี่ปุ่น', 'ญี่ปุ่น'), ('ติมอร์ตะวันออกติมอร์-เลสเต', 'ติมอร์ตะวันออกติมอร์-เลสเต'), ('ตุรกี', 'ตุรกี'), ('เติร์กเมนิสถาน', 'เติร์กเมนิสถาน'), ('ไต้หวัน', 'ไต้หวัน'), ('ทาจิกิสถาน', 'ทาจิกิสถาน'), ('ไทย', 'ไทย'), ('เนปาล', 'เนปาล'), ('บรูไน', 'บรูไน'), ('บังกลาเทศ', 'บังกลาเทศ'), ('บาห์เรน', 'บาห์เรน'), ('ปากีสถาน', 'ปากีสถาน'), ('ปาเลสไตน์', 'ปาเลสไตน์'), ('ฝรั่งเศษ', 'ฝรั่งเศษ'), ('พม่าเมียนมา', 'พม่าเมียนมา'), ('ฟิลิปปินส์', 'ฟิลิปปินส์'), ('ภูฏาน', 'ภูฏาน'), ('มองโกเลีย', 'มองโกเลีย'), ('มัลดีฟส์', 'มัลดีฟส์'), ('มาเลเซีย', 'มาเลเซีย'), ('เยเมน', 'เยเมน'), ('ลาว', 'ลาว'), ('เลบานอน', 'เลบานอน'), ('เวียดนาม', 'เวียดนาม'), ('ศรีลังกา', 'ศรีลังกา'), ('สหรัฐอาหรับเอมิเรตส์', 'สหรัฐอาหรับเอมิเรตส์'), ('สิงคโปร์', 'สิงคโปร์'), ('อัฟกานิสถาน', 'อัฟกานิสถาน'), ('อาเซอร์ไบจาน', 'อาเซอร์ไบจาน'), ('อาร์มีเนีย', 'อาร์มีเนีย'), ('อินเดีย', 'อินเดีย'), ('อินโดนีเซีย', 'อินโดนีเซีย'), ('อิรัก', 'อิรัก'), ('อิสราเอล', 'อิสราเอล'), ('อิหร่าน', 'อิหร่าน'), ('อุซเบกิสถาน', 'อุซเบกิสถาน'), ('โอมาน', 'โอมาน'), ('อังกฤษ', 'อังกฤษ')], max_length=140, verbose_name='LanguageName')),
                ('score', models.DecimalField(decimal_places=20, default=0.0, max_digits=30, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='LanguageScore')),
                ('sumscore', models.DecimalField(blank=True, decimal_places=0, max_digits=30, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='LanguageSumScore')),
                ('accountid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('educationid', models.AutoField(primary_key=True, serialize=False, verbose_name='EducationId')),
                ('datestart', models.DateField()),
                ('dateend', models.DateField()),
                ('name', models.CharField(max_length=140, verbose_name='EducationName')),
                ('degree', models.CharField(choices=[('มัธยมศึกษา', 'มัธยมศึกษา'), ('ประกาศนียบัตรวิชาชีพ (ปวช.)', 'ประกาศนียบัตรวิชาชีพ (ปวช.)'), ('ประกาศนียบัตรวิชาชีพชั้นสูง (ปวส.)', 'ประกาศนียบัตรวิชาชีพชั้นสูง (ปวส.)'), ('ปริญญาตรี', 'ปริญญาตรี'), ('ปริญญาโท', 'ปริญญาโท'), ('ปริญญาเอก', 'ปริญญาเอก')], max_length=150)),
                ('accountid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
