# Generated by Django 3.1.5 on 2021-01-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skillid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
