# Generated by Django 3.1.4 on 2020-12-29 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='commencementday',
            field=models.DateField(default=datetime.datetime(2020, 12, 30, 1, 59, 8, 718615)),
        ),
    ]
