# Generated by Django 3.1.5 on 2021-02-04 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='account',
            new_name='accountid',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='account',
            new_name='accountid',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='account',
            new_name='accountid',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='account',
            new_name='accountid',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='account',
            new_name='accountid',
        ),
    ]
