# Generated by Django 3.1.4 on 2020-12-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201230_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='commencementday',
            field=models.DateField(),
        ),
    ]
