# Generated by Django 3.1.4 on 2021-01-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20201230_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.IntegerField(default='151515151115'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four')], default='1', max_length=6),
        ),
    ]
