# Generated by Django 3.1.5 on 2021-03-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20210310_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='detail',
        ),
    ]
